input {
  file {
    path => "/var/www/html/sagit/var/log/dev.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => { "message" => "%{LOGLEVEL:level} %{GREEDYDATA:message}" }
  }
  date {
    match => [ "timestamp", "ISO8601" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "symfony-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
